version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_service
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth_network

  # 认证服务
  auth-service:
    build: .
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - DB_NAME=auth_service
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRATION=24
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - SMTP_FROM=your-email@gmail.com
      - PORT=8080
      - HOST=0.0.0.0
      - GIN_MODE=release
    depends_on:
      - mysql
    networks:
      - auth_network

volumes:
  mysql_data:

networks:
  auth_network:
    driver: bridge 